# One of these will show up when someone dies
Dead-Messages:
  - '&7&oI think you did a pretty good job so far...'
  - '&7&oWhat now?'
  - '&7&oHaha! Gotcha!'

Chests:
  default:
    InstantKill: false
    Damage: 4.0
    PotionEffects:
      - 'SLOW:60:3'